// ==UserScript==
// @name         baijiahao-fucker
// @namespace    http://tampermonkey.net/
// @include      http://www.baidu.com/s*
// @include      https://www.baidu.com/s*
// @description  删除搜索结果中关于百家号与百度视频的内容
// @author       LuRenJiasWorld
// @grant        GM.xmlHttpRequest
// @run-at       document-end
// @version	     0.20
// @connect      https://baijiahao-fucker.live2.fun
// ==/UserScript==

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('g h="0.20";(3(){x();y();z()})();g A=W.Y.j;B(()=>{2 C=W.Y.j;4(C!==A){2 k=B(()=>{4($("#1p").m!==1){z();D(k)}},10);A=C}},1q);3 x(){n.o({p:"r",e:"E://F-G.H.I/f/f/x",s:J,Z:3(a){1r(a.K)}})}3 t(a){2 L=$("#1s").1t();2 6=M();n.o({p:"r",e:"E://F-G.H.I/f/f/t?11="+6+"&h="+h+"&1u="+a+"&L="+L,s:J})}3 y(){2 6=M();n.o({p:"r",e:"E://F-G.H.I/f/f/y?11="+6+"&h="+h,s:1v})}3 M(){2 6=12.13;4(6){N 6}u{6=14(1w);12.1x("13",6);N 6}}3 14(a){g b="";g c="1y";1z(g i=0;i<a;i++)b+=c.1A(15.1B(15.1C()*c.m));N b}3 z(){\'1D 1E\';2 16=$(\'#1F a[j^="1G://17.18.19/1H?e="]\');2 O=$(\'.c-1I\');2 w=$(\'.1J-1K-w-1L\');2 1M=0;2 d=0;2 1a=$(".1b");2 1c=$(".1b").P();16.1N(3(i,v){2 e=$(1d).1e(\'j\');(3(b,c){b=b.1f("1g")<0?b+"&1O=&1g=":b;n.o({p:"r",e:b,s:J,1P:{"1Q-1R":"1S/5.0 (1T; 1U 1V 1W X 1X) 1Y/1h.1i (1Z, 21 22) 23/24.0.25.26 27/1h.1i","Q":"P/28,1j/29+1k,1j/1k;q=0.9,1l/2a,1l/2b,*/*;q=0.8","2c":"17.18.19","Q-2d":"R-2e,R;q=0.9,2f;q=0.8,R-2g;q=0.7","2h":"1m-1n","2i-2j":"1m-1n","Q-2k":"2l, 2m, 2n","2o":"2p-2q"},Z:3(a){2 S=/2r=[\'|"]([^\'|"]+)/;4(S.2s(a.K)){2 T=a.K.2t(S)[1];4(T.1f(\'2u\')!==-1){d++;$(c).2v(\'.c-2w\').U();4(!O.2x().m){O.1o().U()}}u{$(c).1e(\'j\',T)}1a.P(1c+"，其中包含"+d+"个百家号链接，已全部去除")}},})})(e,1d)});2 l=d;2 V=0;2 k=B(()=>{4(l!==d){l=d}u 4(d!==0&&l!==0){t(d);D(k)}u 4(d===0&&l===0&&V>2y){t(d);D(k)}V++},2z);4(w.m!==0){w.1o().U()}}',62,160,'||let|function|if||id|||||||bjhCounter|url|index|var|version||href|interval|bjhCounterTmp|length|GM|xmlHttpRequest|method||GET|async|statistic|else||video|config|register|fuckBaijiahao|urlStore|setInterval|currentUrl|clearInterval|https|baijiahao|fucker|live2|fun|true|responseText|keyword|idGenerator|return|top|text|Accept|zh|reg|realUrl|remove|logCounter|window||location|onload||userFingerPrint|localStorage|fuckBaijiahaoID|getRandomStr|Math|tags|www|baidu|com|resultCounter|nums_text|resultCounterText|this|attr|indexOf|eqid|537|36|application|xml|image|no|cache|parent|_mask|1000|eval|kw|val|count|false|32|setItem|ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789|for|charAt|floor|random|use|strict|content_left|http|link|offset|op|short|pc|counter|each|wd|headers|User|Agent|Mozilla|Macintosh|Intel|Mac|OS|10_12_6|AppleWebKit|KHTML||like|Gecko|Chrome|71|3578|98|Safari|html|xhtml|webp|apng|Host|Language|CN|en|TW|Pragma|Cache|Control|Encoding|gzip|deflate|br|Connection|keep|alive|URL|test|match|baijia|parents|container|children|500|200'.split('|'),0,{}))